"""empty message

Revision ID: 21479f4fcc4c
Revises: aaabf3672e70
Create Date: 2023-09-22 07:55:28.422755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21479f4fcc4c'
down_revision = 'aaabf3672e70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
