"""empty message

Revision ID: aaabf3672e70
Revises: 416d1fa433d4
Create Date: 2023-09-22 07:14:58.830470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaabf3672e70'
down_revision = '416d1fa433d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.alter_column('balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('number',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('card_cvv')
        batch_op.drop_column('card_expiration_date')
        batch_op.drop_column('card_number')
        batch_op.drop_column('card_holder_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_holder_name', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('card_number', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('card_expiration_date', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('card_cvv', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.alter_column('number',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)

    # ### end Alembic commands ###
